services:
  db:
    image: postgres:15
    container_name: cmpc_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cmpc_libros
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: cmpc_backend
    command: npm run start:dev
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - ./backend/.env
  frontend:
      build:
        context: ./frontend
      container_name: cmpc_frontend
      command: npm run dev
      working_dir: /usr/src/app
      volumes:
        - ./frontend:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - "5173:5173"
      depends_on:
        - backend
      environment:
        - VITE_API_URL=http://localhost:3001

volumes:
  postgres_data:
